kind: ConfigMap
apiVersion: v1
metadata:
  name: prometheus-k8s-rulefiles
  namespace: "{{ project_name }}"
{% raw %}
data:
  pod-rules.yml: |
    groups:
      - name: kubernetes-apps
        rules:
        - alert: KubePodCrashLooping
          annotations:
            message: Pod {{ $labels.namespace }}/{{ $labels.pod }} ({{ $labels.container }}) is restarting {{ printf "%.2f" $value }} times / 5 minutes.
          expr: |
            rate(kube_pod_container_status_restarts{}[5m]) * 60 * 5 > 2
          for: 5m
          labels:
            severity: critical
        - alert: KubePodNotReady
          annotations:
            message: Pod {{ $labels.namespace }}/{{ $labels.pod }} has been in a non-ready state for longer than 5 minutes.
          expr: |
            sum by (pod)(kube_pod_status_phase{phase=~"Pending|Unknown"}) > 0
          for: 5m
          labels:
            severity: critical
{% endraw %}
