apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: {{ project_name }}
data:
  prometheus.yml: |-
    alerting:
      alertmanagers:
      - static_configs:
        - targets: ['alertmanager.{{ project_name }}.svc.cluster.local:8080']
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
        - targets: ['localhost:9090']

      - job_name: 'kube-state-metrics'
        scrape_interval: 10s
        scrape_timeout: 5s
        static_configs:
        - targets: ['kube-state-metrics.{{ project_name }}.svc.cluster.local:8080']
